# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7580a06317468f7346b984a2f791ba2d20fb55cb6ed4c5dfd8737d31f434d22d7a1091d91277afb1ae636912f4fc2ddf20ae69794e7b1854ad9d9fa7baa5dbc7

test:
  secret_key_base: d385ccc326149244276008d9ad25f8236f813b9dc41c762df5d061f1ce00f5bb39642003029615f76d39d49894a8246f57a2526615d27e13eeb12e737945ff77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
